trigger:
  branches:
    include:
      - main

pr: none

stages:

# -----------------------------
# STAGE 1: VALIDATE
# -----------------------------
- stage: Validate
  displayName: "Validate Terraform"
  jobs:
  - job: Validate
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: TerraformInstaller@1

    - script: rm -rf .terraform .terraform.lock.hcl
      workingDirectory: terraform
      displayName: "Clean Terraform Files"


    - script: |
        echo "RG=$(tfstate_resource_group)"
        echo "SA=$(tfstate_storage_account)"
        echo "CONTAINER=$(tfstate_container)"
      displayName: "Debug backend variables"

    - script: |
        terraform init -upgrade -reconfigure \
          -backend-config="resource_group_name=$(tfstate_resource_group)" \
          -backend-config="storage_account_name=$(tfstate_storage_account)" \
          -backend-config="container_name=$(tfstate_container)" \
          -backend-config="key=dev.tfstate" \
          -backend-config="access_key=$(tfstate_access_key)"
      workingDirectory: $(Build.SourcesDirectory)/terraform
      displayName: "Terraform Init"

    - script: terraform validate
      workingDirectory: terraform
      displayName: "Terraform Validate"


# -----------------------------
# DEV ENVIRONMENT
# -----------------------------
- template: templates/terraform-stage.yml
  parameters:
    environmentName: dev
    displayEnvironmentName: DEV
    variableGroup: dev-terraform-secrets
    dependsOn: Validate
    backendStateKey: dev.tfstate
    createSqlServer: "true"

- template: templates/flyway-stage.yml
  parameters:
    environmentName: dev
    displayEnvironmentName: DEV
    variableGroup: dev-terraform-secrets
    dependsOn: Terraform_dev


# -----------------------------
# TEST ENVIRONMENT
# -----------------------------
- template: templates/terraform-stage.yml
  parameters:
    environmentName: test
    displayEnvironmentName: TEST
    variableGroup: test-terraform-secrets
    dependsOn: Flyway_dev
    backendStateKey: test.tfstate
    createSqlServer: "false"

- template: templates/flyway-stage.yml
  parameters:
    environmentName: test
    displayEnvironmentName: TEST
    variableGroup: test-terraform-secrets
    dependsOn: Terraform_test
