variable "server_name" {}
variable "resource_group_name" {}
variable "location" {}
variable "admin_user" {}
variable "admin_password" {}
variable "database_name" {}
variable "sku" {}
variable "start_ip" {}
variable "end_ip" {}