flyway.url=jdbc:sqlserver://sqlserver-dev-6aljv.database.windows.net:1433;databaseName=sqldb-dev;encrypt=true;trustServerCertificate=false
flyway.user=sqladmin
flyway.password=StrongPassword123!

flyway.schemas=dbo
flyway.baselineOnMigrate=true

flyway.locations=filesystem:./sql
flyway.baselineOnMigrate=true
